P224Allup/Controllers/BasketController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Newtonsoft.Json;
using P224Allup.DAL;
using P224Allup.Models;
using P224Allup.ViewModels.Basket;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace P224Allup.Controllers
{
    
    public class BasketController : Controller
    {
        private readonly AllupDbContext _context;

        public BasketController(AllupDbContext context)
        {
            _context = context;
        }
        public async Task<IActionResult> Index()
        {
            string cookieBasket = HttpContext.Request.Cookies["basket"];

            List<BasketVM> basketVMs = null;

            if (cookieBasket != null)
            {
                basketVMs = JsonConvert.DeserializeObject<List<BasketVM>>(cookieBasket);
            }
            else
            {
                basketVMs = new List<BasketVM>();
            }

            foreach (BasketVM basketVM in basketVMs)
            {
                Product dbProduct = await _context.Products.FirstOrDefaultAsync(p => p.Id == basketVM.ProductId);
                basketVM.Image = dbProduct.MainImage;
                basketVM.Price = dbProduct.DiscountPrice > 0 ? dbProduct.DiscountPrice : dbProduct.Price;
                basketVM.ExTax = dbProduct.ExTax;
                basketVM.Title = dbProduct.Title;
            }

            return View(basketVMs);
        }

        public async Task<IActionResult> GetBasket()
        {
            string cookieBasket = HttpContext.Request.Cookies["basket"];

            List<BasketVM> basketVMs = null;

            if (cookieBasket != null)
            {
                basketVMs = JsonConvert.DeserializeObject<List<BasketVM>>(cookieBasket);
            }
            else
            {
                basketVMs = new List<BasketVM>();
            }

            foreach (BasketVM basketVM in basketVMs)
            {
                Product dbProduct = await _context.Products.FirstOrDefaultAsync(p => p.Id == basketVM.ProductId);
                basketVM.Image = dbProduct.MainImage;
                basketVM.Price = dbProduct.DiscountPrice > 0 ? dbProduct.DiscountPrice : dbProduct.Price;
                basketVM.ExTax = dbProduct.ExTax;
                basketVM.Title = dbProduct.Title;
            }

            return PartialView("_BasketPartial", basketVMs);
        }

        public async Task<IActionResult> GetCard()
        {
            string cookieBasket = HttpContext.Request.Cookies["basket"];

            List<BasketVM> basketVMs = null;

            if (cookieBasket != null)
            {
                basketVMs = JsonConvert.DeserializeObject<List<BasketVM>>(cookieBasket);
            }
            else
            {
                basketVMs = new List<BasketVM>();
            }

            foreach (BasketVM basketVM in basketVMs)
            {
                Product dbProduct = await _context.Products.FirstOrDefaultAsync(p => p.Id == basketVM.ProductId);
                basketVM.Image = dbProduct.MainImage;
                basketVM.Price = dbProduct.DiscountPrice > 0 ? dbProduct.DiscountPrice : dbProduct.Price;
                basketVM.ExTax = dbProduct.ExTax;
                basketVM.Title = dbProduct.Title;
            }

            return PartialView("_BasketIndexPartial", basketVMs);
        }

        public async Task<IActionResult> Update(int? id, int? count)
        {
            if (id == null) return BadRequest();

            Product product = await _context.Products.FirstOrDefaultAsync(p => p.Id == id);

            if (product == null) return NotFound();

            string cookieBasket = HttpContext.Request.Cookies["basket"];

            List<BasketVM> basketVMs = null;

            if (cookieBasket != null)
            {
                basketVMs = JsonConvert.DeserializeObject<List<BasketVM>>(cookieBasket);

                if (!basketVMs.Any(b => b.ProductId == id))
                {
                    return NotFound();
                }

                basketVMs.Find(b => b.ProductId == id).Count = (int)count;
            }
            else
            {
                return BadRequest();
            }

            cookieBasket = JsonConvert.SerializeObject(basketVMs);
            HttpContext.Response.Cookies.Append("basket", cookieBasket);

            foreach (BasketVM basketVM in basketVMs)
            {
                Product dbProduct = await _context.Products.FirstOrDefaultAsync(p => p.Id == basketVM.ProductId);
                basketVM.Image = dbProduct.MainImage;
                basketVM.Price = dbProduct.DiscountPrice > 0 ? dbProduct.DiscountPrice : dbProduct.Price;
                basketVM.ExTax = dbProduct.ExTax;
                basketVM.Title = dbProduct.Title;
            }

            return PartialView("_BasketIndexPartial", basketVMs);
        }

        public async Task<IActionResult> DeleteCard(int? id)
        {
            if (id == null) return BadRequest();

            Product product = await _context.Products.FirstOrDefaultAsync(p => p.Id == id);

            if (product == null) return NotFound();

            string cookieBasket = HttpContext.Request.Cookies["basket"];

            List<BasketVM> basketVMs = null;

            if (cookieBasket != null)
            {
                basketVMs = JsonConvert.DeserializeObject<List<BasketVM>>(cookieBasket);

                BasketVM basketVM = basketVMs.FirstOrDefault(b => b.ProductId == id);

                if (basketVM== null)
                {
                    return NotFound();
                }

                basketVMs.Remove(basketVM);
            }
            else
            {
                return BadRequest();
            }

            cookieBasket = JsonConvert.SerializeObject(basketVMs);
            HttpContext.Response.Cookies.Append("basket", cookieBasket);

            foreach (BasketVM basketVM in basketVMs)
            {
                Product dbProduct = await _context.Products.FirstOrDefaultAsync(p => p.Id == basketVM.ProductId);
                basketVM.Image = dbProduct.MainImage;
                basketVM.Price = dbProduct.DiscountPrice > 0 ? dbProduct.DiscountPrice : dbProduct.Price;
                basketVM.ExTax = dbProduct.ExTax;
                basketVM.Title = dbProduct.Title;
            }

            return PartialView("_BasketIndexPartial", basketVMs);
        }

        public async Task<IActionResult> DeleteBasket(int? id)
        {
            if (id == null) return BadRequest();

            Product product = await _context.Products.FirstOrDefaultAsync(p => p.Id == id);

            if (product == null) return NotFound();

            string cookieBasket = HttpContext.Request.Cookies["basket"];

            List<BasketVM> basketVMs = null;

            if (cookieBasket != null)
            {
                basketVMs = JsonConvert.DeserializeObject<List<BasketVM>>(cookieBasket);

                BasketVM basketVM = basketVMs.FirstOrDefault(b => b.ProductId == id);

                if (basketVM == null)
                {
                    return NotFound();
                }

                basketVMs.Remove(basketVM);
            }
            else
            {
                return BadRequest();
            }

            cookieBasket = JsonConvert.SerializeObject(basketVMs);
            HttpContext.Response.Cookies.Append("basket", cookieBasket);

            foreach (BasketVM basketVM in basketVMs)
            {
                Product dbProduct = await _context.Products.FirstOrDefaultAsync(p => p.Id == basketVM.ProductId);
                basketVM.Image = dbProduct.MainImage;
                basketVM.Price = dbProduct.DiscountPrice > 0 ? dbProduct.DiscountPrice : dbProduct.Price;
                basketVM.ExTax = dbProduct.ExTax;
                basketVM.Title = dbProduct.Title;
            }

            return PartialView("_BasketPartial", basketVMs);
        }
    }
}

P224Allup/Controllers/ProductController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using P224Allup.DAL;
using P224Allup.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using P224Allup.ViewModels.Basket;
using Newtonsoft.Json;

namespace P224Allup.Controllers
{
    public class ProductController : Controller
    {
        private readonly AllupDbContext _context;

        public ProductController(AllupDbContext context)
        {
            _context = context;
        }

        public IActionResult Index()
        {
            return View();
        }

        public async Task<IActionResult> DetailModal(int? id)
        {
            if (id == null) return BadRequest();

            Product product = await _context.Products.Include(p=>p.ProductImages).FirstOrDefaultAsync(p => p.Id == id && !p.IsDeleted);

            if (product == null) return NotFound();

            return PartialView("_ProductDetailPartial",product);
        }

        public async Task<IActionResult> AddBasket(int? id, int count = 1)
        {
            if (id == null) return BadRequest();

            Product product = await _context.Products.FirstOrDefaultAsync(p => p.Id == id);

            if (product == null) return NotFound();

            string cookieBasket = HttpContext.Request.Cookies["basket"];

            List<BasketVM> basketVMs = null;

            if (cookieBasket != null)
            {
                basketVMs = JsonConvert.DeserializeObject<List<BasketVM>>(cookieBasket);

                if (basketVMs.Any(b=>b.ProductId == id))
                {
                    basketVMs.Find(b => b.ProductId == id).Count += count;
                }
                else
                {
                    #region old
                    //BasketVM basketVM = new BasketVM
                    //{
                    //    ProductId = (int)id,
                    //    Count = count
                    //};

                    //basketVMs.Add(basketVM);
                    #endregion

                    basketVMs.Add(new BasketVM
                    {
                        ProductId = (int)id,
                        Count = count
                    });
                }
            }
            else
            {
                basketVMs = new List<BasketVM>();
                basketVMs.Add(new BasketVM
                {
                    ProductId = (int)id,
                    Count = count
                });
            }

            cookieBasket = JsonConvert.SerializeObject(basketVMs);
            HttpContext.Response.Cookies.Append("basket", cookieBasket);

            foreach (BasketVM basketVM in basketVMs)
            {
                Product dbProduct = await _context.Products.FirstOrDefaultAsync(p => p.Id == basketVM.ProductId);
                basketVM.Image = dbProduct.MainImage;
                basketVM.Price = dbProduct.DiscountPrice > 0 ? dbProduct.DiscountPrice : dbProduct.Price;
                basketVM.ExTax = dbProduct.ExTax;
                basketVM.Title = dbProduct.Title;
            }

            return PartialView("_BasketPartial",basketVMs);
        }
    }
}

P224Allup/Views/Shared/_BasketIndexPartial.cshtml
@model List<BasketVM>
@{ 
    double subTotal = 0;
    double tax = 0;
    double total = 0;
    foreach (var item in Model)
    {
        total += (item.Price * item.Count) + (item.ExTax * item.Count);
    }
}
<div class="col-xl-8">
    <div class="shopping-cart mt-25">
        <h4 class="allup-title">Shopping Cart</h4>

        <div class="shopping-cart-table table-responsive">
            <table class="table">
                <thead>
                    <tr>
                        <th class="image">Image</th>
                        <th class="product">Product</th>
                        <th class="price">Price</th>
                        <th class="quantity">Quantity</th>
                        <th class="total">Total</th>
                        <th class="delete">Delete</th>
                    </tr>
                </thead>
                <tbody>
                    @foreach (BasketVM basketVM in Model)
                    {
                        <tr>
                            <td>
                                <div class="product-image">
                                    <img style="width:50%" src="assets/images/product/@basketVM.Image" alt="cart">
                                </div>
                            </td>
                            <td>
                                <div class="product-title">
                                    <h4 class="title"><a href="single-product.html">@basketVM.Title</a></h4>
                                </div>
                            </td>
                            <td>
                                <div class="product-price">
                                    <span class="price">€@basketVM.Price</span>
                                </div>
                            </td>
                            <td>
                                <div class="product-quantity">
                                    <div class="quantity mt-15 d-flex">
                                        <a asp-action="update" asp-controller="basket" asp-route-id="@basketVM.ProductId" class="basketUpdate subCount btn border"><i class="fal fa-minus"></i></a>
                                        <input type="text" class="basketItemCount" value="@basketVM.Count" />
                                        <a asp-action="update" asp-controller="basket" asp-route-id="@basketVM.ProductId" class="basketUpdate addCount btn border"><i class="fal fa-plus"></i></a>
                                    </div>
                                </div>
                            </td>
                            <td>
                                <div class="product-total">
                                    <span class="total-amount">€@((basketVM.Count * basketVM.Price).ToString("0.00"))</span>
                                </div>
                            </td>
                            <td>
                                <div class="product-delete">
                                    <a class="deletecard" asp-action="DeleteCard" asp-route-id="@basketVM.ProductId"><i class="fal fa-trash-alt"></i></a>
                                </div>
                            </td>
                        </tr>
                        subTotal += (basketVM.Price * basketVM.Count);
                        tax += (basketVM.ExTax * basketVM.Count);
                    }
                </tbody>
            </table>
        </div>
    </div>
</div>
<div class="col-xl-4">
    <div class="row">
        <div class="col-xl-12 col-md-6">
            <div class="cart-coupon mt-30">
                <h5 class="title">Discount Coupon Code</h5>
                <form action="#">
                    <div class="single-form coupon-form d-flex flex-wrap">
                        <input type="text" placeholder="Coupon Code">
                        <button class="main-btn">Apply Coupon</button>
                    </div>
                </form>
            </div>
        </div>
        <div class="col-xl-12 col-md-6">
            <div class="cart-total mt-30">
                <div class="sub-total">
                    <div class="single-total">
                        <span class="cart-value">Subtotal</span>
                        <span class="cart-amount">€@total.ToString("0.00")</span>
                    </div>
                    <div class="single-total">
                        <span class="cart-value">Shipping Cost</span>
                        <span class="cart-amount">€3.90</span>
                    </div>
                </div>
                <div class="total">
                    <div class="single-total">
                        <span class="cart-value">Total (tax excl.)</span>
                        <span class="cart-amount">€@tax.ToString("0.00")</span>
                    </div>
                    <div class="single-total">
                        <span class="cart-value">Taxes</span>
                        <span class="cart-amount">€@tax.ToString("0.00")</span>
                    </div>
                </div>
                <div class="cart-total-btn text-right">
                    <a class="main-btn" href="#">Proceed to Checkout</a>
                </div>
            </div>
        </div>
    </div>
</div>

P224Allup/Views/Shared/_BasketPartial.cshtml
@model IEnumerable<BasketVM>
@{
    double subTotal = 0;
    double tax = 0;
    double total = 0;
    foreach (var item in Model)
    {
        total += (item.Price * item.Count) + (item.ExTax * item.Count);
    }
}
<div class="cart-btn">
    <a asp-action="Index" asp-controller="Basket">
        <i class="icon ion-bag"></i>
        <span class="text">Cart :</span>
        <span class="total">$@total.ToString("0.00")</span>
        <span class="count">@Model.Count()</span>
    </a>
</div>
<div class="mini-cart">
    <ul class="cart-items">
        @foreach (BasketVM basketVM in Model)
        {
            <li>
                <div class="single-cart-item d-flex">
                    <div class="cart-item-thumb">
                        <a href="single-product.html"><img src="~/assets/images/product/@basketVM.Image" alt="product"></a>
                        <span class="product-quantity">@(basketVM.Count)x</span>
                    </div>
                    <div class="cart-item-content media-body">
                        <h5 class="product-name"><a href="single-product.html">@basketVM.Title</a></h5>
                        <span class="product-price">€@basketVM.Price.ToString("0.00")</span>
                        <a asp-controller="Basket" asp-action="DeleteBasket" asp-route-id="@basketVM.ProductId" class="product-close deletebasket"><i class="fal fa-times"></i></a>
                    </div>
                </div>
            </li>
            subTotal += (basketVM.Price * basketVM.Count);
            tax += (basketVM.ExTax * basketVM.Count);
        }

    </ul>
    <div class="price_content">
        <div class="cart-subtotals">
            <div class="products price_inline">
                <span class="label">Subtotal</span>
                <span class="value">€@subTotal.ToString("0.00")</span>
            </div>
            <div class="shipping price_inline">
                <span class="label">Shipping</span>
                <span class="value">€7.00</span>
            </div>
            <div class="tax price_inline">
                <span class="label">Taxes</span>
                <span class="value">€@tax.ToString("0.00")</span>
            </div>
        </div>
        <div class="cart-total price_inline">
            <span class="label">Total</span>
            <span class="value">€@(total.ToString("0.00"))</span>
        </div>
    </div> <!-- price content -->
    <div class="checkout text-center">
        <a href="checkout.html" class="main-btn">Checkout</a>
    </div>
</div> <!-- mini cart -->

P224Allup/Views/Shared/_ProductDetailPartial.cshtml
@model Product
<div class="modal-header">
    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
        <i class="fal fa-times"></i>
    </button>
</div>
<div class="modal-body">
    <div class="row">
        <div class="col-md-6">
            <div class="product-quick-view-image mt-30">
                <div class="quick-view-image">
                    @foreach (ProductImage productImage in Model.ProductImages)
                    {
                        <div class="single-view-image">
                            <img src="~/assets/images/product/@productImage.Image" alt="product">
                        </div>
                    }
                </div>
                <ul class="quick-view-thumb">
                    @foreach (ProductImage productImage in Model.ProductImages)
                    {
                        <li>
                            <div class="single-thumb">
                                <img src="~/assets/images/product/@productImage.Image" alt="">
                            </div>
                        </li>
                    }
                </ul>
            </div> <!-- Modal Quick View Image -->
        </div>
        <div class="col-md-6">
            <div class="product-quick-view-content mt-30">
                <h3 class="product-title">@Model.Title</h3>
                <p class="reference">Reference: demo_12</p>
                <ul class="rating">
                    <li class="rating-on"><i class="fas fa-star"></i></li>
                    <li class="rating-on"><i class="fas fa-star"></i></li>
                    <li class="rating-on"><i class="fas fa-star"></i></li>
                    <li class="rating-on"><i class="fas fa-star"></i></li>
                    <li class="rating-on"><i class="fas fa-star"></i></li>
                </ul>
                <div class="product-prices">
                    @if (Model.DiscountPrice > 0)
                    {
                        <span class="sale-price"> €@Model.Price.ToString("0.00")</span>
                        <span class="regular-price">€@Model.DiscountPrice.ToString("0.00")</span>
                        <span class="save">Save @((((Model.Price * 100) / Model.DiscountPrice)-100).ToString("0.00"))%</span>
                    }
                    else
                    {
                        <span class="regular-price">€@Model.Price.ToString("0.00")</span>
                    }
                </div>
                <p class="product-description">@Model.Description</p>
                <div class="product-size-color flex-wrap">
                    <div class="product-quantity">
                        <h5 class="title">Quantity</h5>
                        <form id="basketform" method="get" asp-controller="product" asp-action="AddBasket" asp-route-id="@Model.Id" >
                            <div class="quantity d-flex">
                                <button type="button" id="sub" class="sub"><i class="fal fa-minus"></i></button>
                                <input type="text" id="productcount" name="count" value="1" />
                                <button type="button" id="add" class="add"><i class="fal fa-plus"></i></button>
                            </div>
                        </form>
                    </div>
                </div>
                <div class="product-add-cart">
                    <button id="addbasketbtn" type="submit" form="basketform"><i class="icon ion-bag"></i> Add to cart</button>
                </div>
                <div class="product-wishlist-compare">
                    <ul class="d-flex flex-wrap">
                        <li><a href="#"><i class="fal fa-heart"></i> Add to wishlist</a></li>
                        <li><a href="#"><i class="fal fa-repeat"></i> Add to compare</a></li>
                    </ul>
                </div>
                <div class="product-share d-flex">
                    <p>Share</p>
                    <ul class="social media-body">
                        <li><a href="#"><i class="fab fa-facebook-f"></i></a></li>
                        <li><a href="#"><i class="fab fa-twitter"></i></a></li>
                        <li><a href="#"><i class="fab fa-google"></i></a></li>
                        <li><a href="#"><i class="fab fa-pinterest-p"></i></a></li>
                    </ul>
                </div>
            </div> <!-- Modal Quick View Content -->
        </div>
    </div> <!-- row -->
</div>  <!-- Modal Body -->

P224Allup/Views/Shared/_ProductListPartial.cshtml
@model IEnumerable<Product>
@{ 
    int productCount = 0;
}
<div class="product-items">
    <div class="row product-active">
        @for (int i = 0; i < Math.Ceiling((double)Model.Count() / 2); i++)
        {
        <div class="col-lg-2">
            @foreach (Product product in Model.Skip(productCount).Take(2))
            {
                <div class="single-product mt-30">
                    <div class="product-image">
                        <a href="single-product.html">
                            <img class="first-image" src="~/assets/images/product/@product.MainImage" alt="product">
                            <img class="second-image" src="~/assets/images/product/@product.HoverImage" alt="product">
                        </a>
                        <ul class="product-meta">
                            <li><a class="addbasketlink" asp-controller="product" asp-action="AddBasket" asp-route-id="@product.Id"><i class="icon ion-bag"></i></a></li>
                            <li><a href="#"><i class="icon ion-android-favorite-outline"></i></a></li>
                            <li><a href="#"><i class="icon ion-android-options"></i></a></li>
                            <li><a class="productdetail" data-toggle="modal" data-target="#productQuickModal" asp-controller="Product" asp-action="DetailModal" asp-route-id="@product.Id"><i class="icon ion-android-open"></i></a></li>
                        </ul>
                    </div>
                    <div class="product-content">
                        <ul class="product-rating">
                            <li><i class="fas fa-star"></i></li>
                            <li><i class="fas fa-star"></i></li>
                            <li><i class="fas fa-star"></i></li>
                            <li><i class="fas fa-star"></i></li>
                            <li><i class="fas fa-star"></i></li>
                        </ul>
                        <h4 class="product-title"><a href="single-product.html">Cale 6 eu accumsan massa facilisis Madden by Steve</a></h4>
                        <div class="product-price">
                            @if (product.DiscountPrice > 0)
                            {
                                <span class="regular-price">€@product.Price.ToString("0.00")</span>
                                <span class="price-sale">€@product.DiscountPrice.ToString("0.00")</span>
                            }
                            else
                            {
                                <span class="price-sale">€@product.Price.ToString("0.00")</span>
                            }
                        </div>
                    </div>
                </div> <!-- single product -->
                productCount++;
            }
        </div>
        }

    </div> <!-- row -->
</div> <!-- product items -->

P224Allup/Views/Shared/_RegisterPartial.cshtml
@model RegisterVM

<form method="post">
    <div class="text-danger" asp-validation-summary="ModelOnly"></div>
    <div class="single-form">
        <input asp-for="FullName" placeholder="Full Name">
    </div>
    <div class="single-form">
        <input asp-for="Email" placeholder="Email Address">
    </div>
    <div class="single-form">
        <input asp-for="UserName" placeholder="Username">
    </div>
    <div class="single-form">
        <input asp-for="Password" placeholder="Password">
    </div>
    <div class="single-form">
        <input asp-for="ConfirmPassword" placeholder="Confirm Password">
    </div>

    <div class="single-form">
        <button class="main-btn main-btn-2">Register</button>
    </div>
</form>

@section Script{ 
<partial name="_ValidationFormScriptPartial">
}

P224Allup/Views/Shared/_ValidationFormScriptPartial.cshtml
<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery-validate/1.19.3/jquery.validate.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery-validation-unobtrusive/3.2.12/jquery.validate.unobtrusive.min.js"></script>